### ISSUE TITLE
Gallery takes up a lot of time while loading and want to change some pics and info.

### ISSUE THREAD

**Issue by AdityaSeth777** [subhadeep3902/IIC-TMSL-WEBSITE#1]
No doubt this is one of the best websites I have seen but this needs some tweaking.
After the end of the selection drive, I would like to contribute to your code.

Aditya.

**Comment by subhadeeproy3902** [comment]
Alryt ✌🏻✌🏻...the gallery page is taking a lot time due to so many images in it 😅😅

**Comment by AdityaSeth777** [comment]
That's fine.
Everything can be tweaked :D

**Comment by AdityaSeth777** [comment]
@itz-coder-subha 
I am closing this issue for now.
